# Generated by Django 4.2.9 on 2024-01-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kids_school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('school_location', models.CharField(max_length=255)),
                ('school_owner', models.CharField(max_length=255)),
                ('manager_email', models.CharField(max_length=255)),
                ('manager_tel', models.CharField(max_length=255)),
            ],
        ),
    ]
